### ISSUE TITLE
Binaries don't work on Ubuntu 14.04

### ISSUE THREAD

**Issue by fiatjaf** [BurntSushi/xsv#2] opened 2015-02-23 10:43 UTC
```
fiatjaf@spooner ~> 
curl -sOL https://github.com/BurntSushi/xsv/releases/download/0.8.14/xsv-0.8.14-x86_64-unknown-linux-gnu.tar.gz
fiatjaf@spooner ~> tar xf xsv-0.8.14-x86_64-unknown-linux-gnu.tar.gz
fiatjaf@spooner ~> cd xsv-0.8.14-x86_64-unknown-linux-gnu/
fiatjaf@spooner ~/xsv-0.8.14-x86_64-unknown-linux-gnu> ./xsv --version
Failed to execute process './xsv'. Reason:
exec: Exec format error
The file './xsv' is marked as an executable but could not be run by the operating system.
```

I tested it in two very different machines I have access to with the same result (but coincidentally they both are running Ubuntu 14.04).

**Comment by BurntSushi** [comment] 2015-02-24 12:39
That's a strange error. Can you try the latest release? https://github.com/BurntSushi/xsv/releases

I wonder if this is a dupe of #3, but the error here is quite strange.

**Comment by fiatjaf** [comment] 2015-02-24 13:12
I tried and got the same error.

**Comment by jungle-boogie** [comment] 2015-08-18 05:39
You could run `file` on the xsv to see what the OS identifies it as.

**Comment by BurntSushi** [comment] 2016-09-02 11:37
I don't know how to reproduce the problem in this ticket, but there are [new releases](https://github.com/BurntSushi/xsv/releases) including statically compiled executables for Linux.

**Closed by BurntSushi** 2016-09-02 11:37 UTC
Labels: question
