### ISSUE TITLE
thread '<main>' panicked at 'index out of bounds: the len is 0 but the index is 9', src/select.rs:352

### ISSUE THREAD

**Issue by zacstewart** [BurntSushi/xsv#23] opened 2015-10-12 22:59 UTC
I caught this panic while performing a join:

```
xsv join --no-case url images.csv url machines.csv
thread '<main>' panicked at 'index out of bounds: the len is 0 but the index is 9', src/select.rs:352
Image,index,url,Year,Manufacturer,Model,Title,Serial,Stock,Pricing,Description,index,url
```

I was able to get by it by flipping the two CSVs to be joined.

**Comment by BurntSushi** [comment] 2015-10-12 23:08
@zacstewart Owch. Could you please provide some CSV data that will trigger the error? Thanks!

**Comment by zacstewart** [comment] 2015-10-13 13:31
I think it was an encoding error. I was using the URL column as a foreign key to join these, but ended up needing to add a more regular FK anyway.

In Ruby, I was adding a `Key` column by taking a hash of the URL. I ran into a row with an invalid byte sequence and had to fix it. As a result, xsv no longer fails.

**Comment by BurntSushi** [comment] 2015-10-13 14:16
@zacstewart Understood. `xsv` still shouldn't panic like this on *any* input. If you'd be willing to share data that causes `xsv` to crash, that would be great.

**Comment by zacstewart** [comment] 2015-10-13 14:20
I would, the problem is, I didn't have it in version control. I'm trying to munge some data into shape to on-board a customer and didn't stop to capture a breaking sample. If I catch it again, I'll be sure to save it. Thanks a lot for the tool. I'm finding it very helpful.

**Comment by zacstewart** [comment] 2015-11-01 18:35
I found one!

```
xsv join MachineID data/Train.csv MachineID data/Machine_Appendix.csv
thread '<main>' panicked at 'index out of bounds: the len is 0 but the index is 0', src/select.rs:352
SalesID,SalePrice,MachineID,ModelID,datasource,auctioneerID,YearMade,MachineHoursCurrentMeter,UsageBand,saledate,fiModelDesc,fiBaseModel,fiSecondaryDesc,fiModelSeries,fiModelDescriptor,ProductSize,fiProductClassDesc,state,ProductGroup,ProductGroupDesc,Drive_System,Enclosure,Forks,Pad_Type,Ride_Control,Stick,Transmission,Turbocharged,Blade_Extension,Blade_Width,Enclosure_Type,Engine_Horsepower,Hydraulics,Pushblock,Ripper,Scarifier,Tip_Control,Tire_Size,Coupler,Coupler_System,Grouser_Tracks,Hydraulics_Flow,Track_Type,Undercarriage_Pad_Width,Stick_Length,Thumb,Pattern_Changer,Grouser_Type,Backhoe_Mounting,Blade_Type,Travel_Controls,Differential_Type,Steering_Controls,MachineID,ModelID,fiModelDesc,fiBaseModel,fiSecondaryDesc,fiModelSeries,fiModelDescriptor,fiProductClassDesc,ProductGroup,ProductGroupDesc,MfgYear,fiManufacturerID,fiManufacturerDesc,PrimarySizeBasis,PrimaryLower,PrimaryUpper
```

You can download the relevant CSV files here: https://www.kaggle.com/c/bluebook-for-bulldozers/data

**Comment by Armavica** [comment] 2016-04-23 13:41
Apparently it has to do with dos-style line endings.

```
$ echo -ne 'foo\n1\n' >foo_n.csv
$ echo -ne 'bar\n1\n' >bar_n.csv
$ echo -ne 'foo\r\n1\r\n' >foo_rn.csv
$ echo -ne 'bar\r\n1\r\n' >bar_rn.csv
$ xsv join foo foo_n.csv bar bar_n.csv
foo,bar
1,1
$ xsv join foo foo_rn.csv bar bar_rn.csv
thread '<main>' panicked at 'index out of bounds: the len is 0 but the index is 0', .cargo/registry/src/github.com-88ac128001ac3a9a/xsv-0.9.11/src/select.rs:352
foo,bar
```

**Comment by BurntSushi** [comment] 2016-07-31 19:12
@zacstewart @Armavica This should be fixed. The actual underlying problem was actually the CSV reader. It was delayed in reporting EOF on the stream because of a bug in the state machine when dealing with CRLF data.

**Closed** 2016-07-31 19:11 UTC

**Comment by dvdplm** [comment] 2017-12-06 08:23
@BurntSushi I have a silly newbee question wrt to these kinds of panics. I ran into one in my own code that uses the `redis-rs` crate. I got an empty `redis::Value::Bulk` back from the library and tried to access it and my program panics deep down in `vec.rs`. My question is: is this "ok" and expected behavior or should I report this as a bug on the compiler? The fix on my side was easy enough of course but I'm unsure if I hit a deeper issue or not. Thanks!

**Comment by BurntSushi** [comment] 2017-12-06 11:41
@dvdplm I'd have to see the code. A panic like this is certainly not a bug in the *compiler* itself. If you have a `let x: Option<T> = None;` and then call `x.unwrap()`, then your program will panic, and that is expected behavior.

With that said, end users of a program should never see a panic. A panic indicates a bug in the program, typically because some assumption was made about user input that isn't always true. It is the responsibility of the application to not panic. (Similarly, if a library panics in a way that is undocumented or unexpected, then that is likely also a bug in the library, but it sounds like you tried to unwrap an empty value, which rightfully panic'd.)

**Comment by dvdplm** [comment] 2017-12-06 13:40
> it sounds like you tried to unwrap an empty value, which rightfully panic'd.)

Well, no. Or perhaps implicitly. My program crashes with `thread '<main>' panicked at 'index out of bounds: the len is 0 but the index is 0'` with the backtrace pointing to `vec.rs` doing allocations. The code looks something like this:

```rust
impl redis::FromRedisValue for Message {
    fn from_redis_value(v: &Value) -> RedisResult<Message> {
        match *v {
            Value::Bulk(ref items) => {
               // my code tried to access items[0] etc here; fix was easy enough but the error message looked funky!
               …
            }
      }
```

So, sure, panics can happen, intentionally or not but the question was more: is the error message I ran into (and which led me here) what I should expect when doing silly things like I did or did I run into something deeper. I think the former.

Again, thanks!
}
```

**Comment by BurntSushi** [comment] 2017-12-06 13:44
@dvdplm I haven't used the redis crate so I don't know. If the redis crate provides you with a guarantee that `items` is not empty, then it sounds like a bug in the redis crate. If, however, `items` is allowed to be empty, then handling that case is on you. That in turn means the panic message you saw is indeed expected. That panic happened because you tried to access something that didn't exist. If this were C, you would have invoked undefined behavior and (hopefully, if you're lucky) gotten a segfault.

More specifically, somewhere in the standard library, there is a method that looks like this for `Vec`:

```rust
fn get(&self, i: usize) -> &T {
    if i >= self.len() {
        panic("index out of bounds, got {} but expected index less than {}", i, self.len());
    }
    unsafe {
        // raw pointer arithmetic
    }
}
```

**Comment by zacstewart** [comment] 2017-12-06 13:45
Indexing a vec via brackets is equivalent to `vec.get(0).unwrap()`, so you are probably indexing past the end of your vec and trying to unwrap `None`.

**Comment by dvdplm** [comment] 2017-12-06 14:57
@BurntSushi makes sense, thank you for taking the time. @zacstewart yes, that sums it up.

Sorry for the noise here. :)
