### ISSUE TITLE
Request to add -t for tab-separated file

### ISSUE THREAD

**Issue by xmao** [BurntSushi/xsv#58] opened 2017-02-27 20:40 UTC
csvkit uses -t to specify tab as separator in file, instead of using -d "\t". It's really sweet shortcut.

**Comment by BurntSushi** [comment] 2017-02-27 20:48
Alternatively, name your files `tsv` and xsv will do the right thing.

Otherwise, I think this is a dupe of #44.

**Closed by BurntSushi** 2017-02-27 20:48 UTC

**Comment by dnrce** [comment] 2017-05-19 12:58
I think this is distinct functionality. It's not changing the default (#44), it's simply providing a shorthand for a one-time override. (Though admittedly #44 probably serves my own use case better.)
